version: 2
jobs:
  build:
    docker:
      - image: holmusk/servant-hmac-auth-ci
    steps:
      - checkout
      - restore-cache:
          key: stack-work-{{ checksum "servant-hmac-auth.cabal" }}
      - restore-cache:
          key: stack-global-{{ checksum "stack.yaml" }}
      - run: stack test --fast
      - save_cache:
          key: stack-global-{{ checksum "stack.yaml" }}
          paths:
            - "~/.stack"
      - save_cache:
          key: stack-work-{{ checksum "servant-hmac-auth.cabal" }}
          paths:
            - ".stack-work"

  lint:
    docker:
      - image: holmusk/servant-hmac-auth-ci
    steps:
      - checkout
      - run: /root/.local/bin/hlint .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
